apiVersion: apps/v1
kind: Deployment
metadata:
  name: workoutapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workoutapi
  template:
    metadata:
      labels:
        app: workoutapi
    spec:
      containers:
        - name: workoutapi
          image: workoutapi:latest
          ports:
            - containerPort: 3000
