apiVersion: v1
kind: Service
metadata:
  name: workoutapi-service-dev
  labels:
    app: workoutapi
    environment: dev
spec:
  selector:
    app: workoutapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
