apiVersion: v1
kind: Service
metadata:
  name: blitzapp-service-dev
  labels:
    app: blitzapp
    environment: dev
spec:
  selector:
    app: blitzapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
